name: GrapesJS Qualty Checks
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - name: TS Check
        run: yarn ts:check
      - name: Lint
        run: yarn lint
      - name: Format Check
        run: yarn format:check
      - name: Docs
        run: yarn docs:api
